-- Consolidated Migration for ValueSets Feature
-- Run this in Supabase SQL Editor to initialize the required table

-- 1. Create Table if not exists
CREATE TABLE IF NOT EXISTS "fhir_set_values" (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    set_id text not null,
    set_name text,         -- Added for friendly name
    code text not null,
    display text,
    system text,
    resource_path text,
    hospital_code text,    -- Added for internal mapping
    UNIQUE(set_id, code)
);

-- 2. Enable RLS
ALTER TABLE "fhir_set_values" ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy (Allow public access for this app)
DROP POLICY IF EXISTS "Allow public read/write access" ON "fhir_set_values";
CREATE POLICY "Allow public read/write access" ON "fhir_set_values"
FOR ALL USING (true) WITH CHECK (true);

-- 4. Grant permissions (ensure anon/authenticated can access)
GRANT ALL ON TABLE "fhir_set_values" TO anon;
GRANT ALL ON TABLE "fhir_set_values" TO authenticated;
GRANT ALL ON TABLE "fhir_set_values" TO service_role;
