-- Reset Tables (Drop if exists to ensure clean state with correct constraints)
-- WARNING: This deletes all existing data in these tables.
DROP TABLE IF EXISTS "KPI" CASCADE;
DROP TABLE IF EXISTS "KPI_Detail" CASCADE;

-- Create KPI Table (Aggregated Data)
CREATE TABLE "KPI" (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    department text,
    doctor text,
    indicator_name text,
    indicator_def text,
    numerator integer,
    denominator integer,
    value double precision,
    unit text,
    UNIQUE(department, doctor, indicator_name)
);

-- Create KPI_Detail Table (Transactional Data)
CREATE TABLE "KPI_Detail" (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    department text,
    doctor text,
    indicator_name text,
    indicator_def text,
    patient_id text,
    patient_gender text,
    patient_birthday date,
    status text,
    value double precision,
    numerator integer,
    denominator integer,
    unit text,
    report_date timestamp with time zone,
    admission_date timestamp with time zone,
    discharge_date timestamp with time zone,
    abnormal_reason text
);

-- Enable RLS
ALTER TABLE "KPI" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "KPI_Detail" ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Allow public read/write access" ON "KPI"
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read/write access" ON "KPI_Detail"
FOR ALL USING (true) WITH CHECK (true);
