-- Create fhir_set_values Table (ValueSet Management)
CREATE TABLE IF NOT EXISTS "fhir_set_values" (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    set_id text not null,        -- e.g. 'C_Section_Exclusion_VS'
    code text not null,          -- e.g. '81001C'
    display text,                -- e.g. '葡萄胎或絨毛膜癌除去術'
    system text,                 -- e.g. 'http://tw-health-insurance...'
    resource_path text,          -- e.g. 'Procedure.code', optional hint
    UNIQUE(set_id, code)
);

-- Enable RLS
ALTER TABLE "fhir_set_values" ENABLE ROW LEVEL SECURITY;

-- Create Policies
DROP POLICY IF EXISTS "Allow public read/write access" ON "fhir_set_values";
CREATE POLICY "Allow public read/write access" ON "fhir_set_values"
FOR ALL USING (true) WITH CHECK (true);
