import React, { useState } from 'react';

export function DeployButtons({ measure }: { measure: any }) {
    // Default to localhost, but allow user to change it
    const [fhirUrl, setFhirUrl] = useState('http://localhost:8080/fhir');

    const deployToFHIR = async () => {
        try {
            // 生成 FHIR Measure JSON
            const measureJson = {
                resourceType: 'Measure',
                id: measure.id,
                title: measure.title,
                library: [`Library/${measure.id.replace('measure-', '')}CQL`],
                group: [{
                    population: [
                        { id: 'denominator', criteria: { expression: 'Denominator' } },
                        { id: 'numerator', criteria: { expression: 'Numerator' } }
                    ]
                }]
            };

            // 部署到 HAPI FHIR
            // Strip trailing slash if present
            const baseUrl = fhirUrl.replace(/\/$/, '');
            const targetUrl = `${baseUrl}/Measure/${measure.id}`;

            const response = await fetch(targetUrl, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/fhir+json' },
                body: JSON.stringify(measureJson)
            });

            if (response.ok) {
                alert(`部署成功！可至 ${baseUrl}/Measure 檢視`);
            } else {
                alert('部署失敗: ' + response.statusText);
            }
        } catch (error) {
            console.error('Deploy error:', error);
            alert('部署發生錯誤 (請確認 FHIR Server 是否啟動)');
        }
    };

    const downloadJson = () => {
        const measureJson = {
            resourceType: 'Measure',
            id: measure.id,
            title: measure.title,
            // ... comprehensive structure would go here
            note: "Generated by KPIM Measure Builder"
        };
        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(measureJson, null, 2));
        const downloadAnchorNode = document.createElement('a');
        downloadAnchorNode.setAttribute("href", dataStr);
        downloadAnchorNode.setAttribute("download", measure.id + ".json");
        document.body.appendChild(downloadAnchorNode); // required for firefox
        downloadAnchorNode.click();
        downloadAnchorNode.remove();
    };

    return (
        <div className="flex flex-col gap-4">
            {/* FHIR Server Config */}
            <div className="flex items-center gap-3 bg-white p-3 rounded-lg border shadow-sm max-w-2xl">
                <label className="text-sm font-semibold text-gray-700 whitespace-nowrap">
                    FHIR Endpoint:
                </label>
                <input
                    type="text"
                    value={fhirUrl}
                    onChange={(e) => setFhirUrl(e.target.value)}
                    className="flex-1 p-1.5 border border-gray-300 rounded text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                    placeholder="e.g. http://localhost:8080/fhir or https://hapi.fhir.tw/fhir"
                />
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4 flex-wrap">
                <button
                    className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition flex items-center gap-2 shadow-sm"
                    onClick={deployToFHIR}
                >
                    <span>🚀</span> 部署到 FHIR Server
                </button>
                <button
                    className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 transition flex items-center gap-2 shadow-sm"
                    onClick={downloadJson}
                >
                    <span>💾</span> 下載 JSON 檔案
                </button>
                <button className="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 transition flex items-center gap-2 text-opacity-80 cursor-not-allowed shadow-sm">
                    <span>📊</span> 執行計算 (Comming Soon)
                </button>
            </div>
        </div>
    );
}
