-- Create kpi_definitions table
CREATE TABLE IF NOT EXISTS public.kpi_definitions (
    kpiid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    formula TEXT,
    category VARCHAR(100),
    numerator_name VARCHAR(100),
    denominator_name VARCHAR(100),
    frequency VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for kpi_definitions
ALTER TABLE public.kpi_definitions ENABLE ROW LEVEL SECURITY;

-- Create policy for kpi_definitions (Allow all for authenticated users for now)
CREATE POLICY "Allow all access for authenticated users" ON public.kpi_definitions
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);


-- Create kpi_dl table
CREATE TABLE IF NOT EXISTS public.kpi_dl (
    uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kpiid UUID NOT NULL REFERENCES public.kpi_definitions(kpiid) ON DELETE CASCADE,
    kpi_dl_type INT, -- 1: Denominator, 2: Numerator, 3: Exclusion
    kpi_dl_name VARCHAR(100),
    kpi_dl_condition_id INT GENERATED BY DEFAULT AS IDENTITY,
    kpi_id_fhir_resource VARCHAR(100),
    kpi_dl_condition_value TEXT,
    kpi_dl_notes TEXT,
    kpi_dl_createddate TIMESTAMPTZ DEFAULT now(),
    kpi_dl_create_user VARCHAR(300)
);

-- Enable RLS for kpi_dl
ALTER TABLE public.kpi_dl ENABLE ROW LEVEL SECURITY;

-- Create policy for kpi_dl (Allow all for authenticated users for now)
CREATE POLICY "Allow all access for authenticated users" ON public.kpi_dl
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_kpi_dl_kpiid ON public.kpi_dl(kpiid);
