-- Fix kpi_definitions PK name
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'kpi_definitions' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.kpi_definitions RENAME COLUMN id TO kpiid;
    END IF;
END $$;

-- Ensure kpi_definitions has the new columns from 20260106_kpi_schema_update.sql if missed
ALTER TABLE public.kpi_definitions 
ADD COLUMN IF NOT EXISTS numerator_c VARCHAR(10),
ADD COLUMN IF NOT EXISTS denominator_c VARCHAR(10);

-- Create kpi_dl if it doesn't exist (because previous attempts failed due to FK error)
CREATE TABLE IF NOT EXISTS public.kpi_dl (
    uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kpiid UUID NOT NULL REFERENCES public.kpi_definitions(kpiid) ON DELETE CASCADE,
    kpi_dl_type INT, 
    kpi_dl_name VARCHAR(100),
    kpi_dl_condition_id INT GENERATED BY DEFAULT AS IDENTITY,
    kpi_id_fhir_resource VARCHAR(100),
    kpi_dl_condition_value TEXT,
    kpi_dl_notes TEXT,
    kpi_dl_createddate TIMESTAMPTZ DEFAULT now(),
    kpi_dl_create_user VARCHAR(300),
    source_type VARCHAR(10)
);

-- Ensure RLS on kpi_dl
ALTER TABLE public.kpi_dl ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'kpi_dl' AND policyname = 'Allow all access for authenticated users'
    ) THEN
        CREATE POLICY "Allow all access for authenticated users" ON public.kpi_dl
            FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_kpi_dl_kpiid ON public.kpi_dl(kpiid);
