-- Handle kift_definitions (Renaming or Creating)
DO $$
BEGIN
    -- 1. Try to rename 'factors' if it exists and 'kift_definitions' does not
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'factors') AND NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'kift_definitions') THEN
        ALTER TABLE public.factors RENAME TO kift_definitions;
    END IF;

    -- 2. If 'kift_definitions' exists (either renamed or existed), ensure 'id' is renamed to 'kiftid'
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'kift_definitions') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'kift_definitions' AND column_name = 'id') THEN
            ALTER TABLE public.kift_definitions RENAME COLUMN id TO kiftid;
        END IF;
    ELSE
        -- 3. If it still doesn't exist, Create it
        CREATE TABLE public.kift_definitions (
            kiftid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name VARCHAR(255) NOT NULL,
            description TEXT,
            method VARCHAR(50) DEFAULT 'sum', -- sum, count, distcount
            source_type VARCHAR(50) DEFAULT 'FHIR', -- FHIR, Manual
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now()
        );
        
        -- Enable RLS and Policy
        ALTER TABLE public.kift_definitions ENABLE ROW LEVEL SECURITY;
        
        IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'kift_definitions' AND policyname = 'Allow all access for authenticated users') THEN
             CREATE POLICY "Allow all access for authenticated users" ON public.kift_definitions FOR ALL TO authenticated USING (true) WITH CHECK (true);
        END IF;
    END IF;
END $$;


-- Handle kift_steps (Renaming or Creating)
DO $$
BEGIN
    -- 1. Try to rename 'factor_steps' if it exists
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'factor_steps') AND NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'kift_steps') THEN
        ALTER TABLE public.factor_steps RENAME TO kift_steps;
    END IF;

    -- 2. If 'kift_steps' exists, ensure 'factor_id' is renamed to 'kift_id'
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'kift_steps') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'kift_steps' AND column_name = 'factor_id') THEN
            ALTER TABLE public.kift_steps RENAME COLUMN factor_id TO kift_id;
        END IF;
    ELSE
        -- 3. Create if not exists
        CREATE TABLE public.kift_steps (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            kift_id UUID NOT NULL REFERENCES public.kift_definitions(kiftid) ON DELETE CASCADE,
            step_order INT GENERATED BY DEFAULT AS IDENTITY,
            action VARCHAR(50), -- BASE, AND, OR, EXCLUDE
            value_type VARCHAR(50), -- fhir_filter, kpi, factor
            resource_type VARCHAR(100),
            path VARCHAR(255),
            operator VARCHAR(50),
            value TEXT,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT now()
        );

        ALTER TABLE public.kift_steps ENABLE ROW LEVEL SECURITY;

        IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'kift_steps' AND policyname = 'Allow all access for authenticated users') THEN
            CREATE POLICY "Allow all access for authenticated users" ON public.kift_steps FOR ALL TO authenticated USING (true) WITH CHECK (true);
        END IF;

        CREATE INDEX IF NOT EXISTS idx_kift_steps_kift_id ON public.kift_steps(kift_id);
    END IF;
END $$;


-- Add kift_id to kpi_dl table
DO $$
BEGIN
    -- Ensure kpi_dl exists first (it should) - assuming it does from previous migrations
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'kpi_dl') THEN
         ALTER TABLE public.kpi_dl 
         ADD COLUMN IF NOT EXISTS kift_id UUID REFERENCES public.kift_definitions(kiftid) ON DELETE SET NULL;
         
         CREATE INDEX IF NOT EXISTS idx_kpi_dl_kift_id ON public.kpi_dl(kift_id);
    END IF;
END $$;
