-- Create factors table
CREATE TABLE IF NOT EXISTS public.factors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    method VARCHAR(50) DEFAULT 'sum', -- sum, count, distcount
    source_type VARCHAR(50) DEFAULT 'FHIR', -- FHIR, Manual
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for factors
ALTER TABLE public.factors ENABLE ROW LEVEL SECURITY;

-- Create policy for factors
CREATE POLICY "Allow all access for authenticated users" ON public.factors
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Create factor_steps table
CREATE TABLE IF NOT EXISTS public.factor_steps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    factor_id UUID NOT NULL REFERENCES public.factors(id) ON DELETE CASCADE,
    step_order INT GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR(50), -- BASE, AND, OR, EXCLUDE
    value_type VARCHAR(50), -- fhir_filter, kpi, factor
    resource_type VARCHAR(100),
    path VARCHAR(255),
    operator VARCHAR(50),
    value TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for factor_steps
ALTER TABLE public.factor_steps ENABLE ROW LEVEL SECURITY;

-- Create policy for factor_steps
CREATE POLICY "Allow all access for authenticated users" ON public.factor_steps
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_factor_steps_factor_id ON public.factor_steps(factor_id);
